// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AmbilHalaman(arg1:number):Promise<main.GambarResponse>;

export function AreSwitch(arg1:string,arg2:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function Languages():Promise<main.LanguagesResponse>;

export function ResetDokumen():Promise<Record<string, boolean>>;

export function Terjemahkan(arg1:number,arg2:string,arg3:string,arg4:boolean):Promise<main.TerjemahanResponse>;

export function UploadPDF(arg1:string,arg2:string):Promise<main.UploadResponse>;
