// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AmbilHalaman(arg1) {
  return window['go']['main']['App']['AmbilHalaman'](arg1);
}

export function AreSwitch(arg1, arg2) {
  return window['go']['main']['App']['AreSwitch'](arg1, arg2);
}

export function CekKesiapan() {
  return window['go']['main']['App']['CekKesiapan']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Languages() {
  return window['go']['main']['App']['Languages']();
}

export function ResetDokumen() {
  return window['go']['main']['App']['ResetDokumen']();
}

export function Terjemahkan(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Terjemahkan'](arg1, arg2, arg3, arg4);
}

export function UploadPDF() {
  return window['go']['main']['App']['UploadPDF']();
}
