name: Build Windows Application
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Frontend
        run: |
          cd go\frontend
          npm install
          npm run build

      - name: Build Application (Backend)
        run: |
          cd go
          # CGO dimatikan penuh karena Windows OCR menggunakan Native WinRT API bawaan Windows
          $env:CGO_ENABLED="0"
          
          # Install Wails CLI dan jalankan build dengan flag -s (skipfrontend)
          go run github.com/wailsapp/wails/v2/cmd/wails@latest build -platform windows/amd64 -s

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: go/build/bin/