name: Build Windows Application
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # Menggunakan Chocolatey untuk menginstal Tesseract versi Windows secara instan
      - name: Install Tesseract via Chocolatey
        run: |
          choco install tesseract

      - name: Install MSYS2 & GCC Compiler
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: mingw-w64-ucrt-x86_64-gcc

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Application
        shell: msys2 {0}
        run: |
          export CGO_ENABLED=1
          # Menghubungkan jalur header dan library Tesseract dari Chocolatey ke MSYS2
          export CGO_CFLAGS="-I/c/Program Files/Tesseract-OCR/include"
          export CGO_LDFLAGS="-L/c/Program Files/Tesseract-OCR -ltesseract"
          
          cd go
          wails build -platform windows/amd64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: go/build/bin/*.exe